---
# Title: app-win-template
#
# Author: Bitfinity-NL / L. Rutten
# File: defaults/additional-tasks.yml
#
# Description:
#   Section for additional tasks
#

- name: "Remove Public desktop icon"
  win_file:
    path: "%public%/desktop/{{ pkg_icon_name }}"
    state: absent
  when: pkg_remove_public_desktop_icon == 'true'

- name: "Remove Public start menu icon"
  win_file:
    path: "%ProgramData%/Microsoft/Windows/Start Menu/Programs/{{ pkg_icon_name }}"
    state: absent
  when: pkg_remove_public_start_menu_icon == 'true'

- name: "Create directory location for the FTP server"
  win_file:
    path: "{{ ftp_path }}"
    state: directory

- name: "Transfer configuration file"
  win_template:
    src: FileZilla Server.xml.j2
    dest: "C:\\Program Files (x86)\\FileZilla Server\\FileZilla Server.xml" 
  notify:
    - Restart_Filezilla
